global:
  scrape_interval: 10s
  scrape_timeout: 15s
scrape_configs:
  - job_name: "vmagent"
    static_configs:
      - targets: ["vmagent:8429"]
  - job_name: "victoriametrics"
    static_configs:
      - targets: ["victoriametrics:8428"]
  - job_name: c2-websocket
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - "%{C2_WEBSOCKET_HOST}"
