version: '3'

tasks:
  dev:
    desc: Run the operator frontend with hot reload
    cmds:
      - bun run dev

  studio:
    desc: Run drizzle studio
    cmds:
      - bun run studio

  dbgen:
    desc: Generate the database schema
    cmds:
      - bun run generate

  dbmigrate:
    desc: Migrate the database schema
    cmds:
      - bun run migrate

  format:
    desc: Format & lint the frontend code
    cmds:
      - bun run format && bun run lint
