version: "3"

tasks:
  proto:
    desc: Generate Go code from proto files
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative ./common/entities/*.proto
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative ./common/service/*.proto

  ws-run:
    desc: Run Websocket server
    dir: ./malgo-websocket
    cmds:
      - go run ./cmd/server/main.go

  gw-run:
    desc: Run gRPC Gateway server
    dir: ./malgo-gateway
    cmds:
      - go run ./cmd/server/main.go

  redirector-run:
    desc: Run Redirector server
    dir: ./malgo-redirector
    cmds:
      - go run ./cmd/server/main.go

  format:
    desc: Format Go code
    cmds:
      - go fmt ./...
