// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: common/entities/commands.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Command-related messages
type CreateCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *Header `protobuf:"bytes,1,opt,name=header,proto3,oneof" json:"header,omitempty"`
	SessionId string  `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Command   string  `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	UserId    string  `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *CreateCommand) Reset() {
	*x = CreateCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_entities_commands_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommand) ProtoMessage() {}

func (x *CreateCommand) ProtoReflect() protoreflect.Message {
	mi := &file_common_entities_commands_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommand.ProtoReflect.Descriptor instead.
func (*CreateCommand) Descriptor() ([]byte, []int) {
	return file_common_entities_commands_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCommand) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CreateCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CreateCommand) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *Header `protobuf:"bytes,1,opt,name=header,proto3,oneof" json:"header,omitempty"`
	CommandId string  `protobuf:"bytes,3,opt,name=commandId,proto3" json:"commandId,omitempty"`
}

func (x *CancelCommand) Reset() {
	*x = CancelCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_entities_commands_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelCommand) ProtoMessage() {}

func (x *CancelCommand) ProtoReflect() protoreflect.Message {
	mi := &file_common_entities_commands_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelCommand.ProtoReflect.Descriptor instead.
func (*CancelCommand) Descriptor() ([]byte, []int) {
	return file_common_entities_commands_proto_rawDescGZIP(), []int{1}
}

func (x *CancelCommand) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CancelCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

// Subscription-related messages
type SubscribeToSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *Header `protobuf:"bytes,1,opt,name=header,proto3,oneof" json:"header,omitempty"`
	SessionId string  `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
}

func (x *SubscribeToSession) Reset() {
	*x = SubscribeToSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_entities_commands_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeToSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToSession) ProtoMessage() {}

func (x *SubscribeToSession) ProtoReflect() protoreflect.Message {
	mi := &file_common_entities_commands_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToSession.ProtoReflect.Descriptor instead.
func (*SubscribeToSession) Descriptor() ([]byte, []int) {
	return file_common_entities_commands_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeToSession) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SubscribeToSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SubscribeToProject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *Header `protobuf:"bytes,1,opt,name=header,proto3,oneof" json:"header,omitempty"`
	ProjectId string  `protobuf:"bytes,2,opt,name=projectId,proto3" json:"projectId,omitempty"`
}

func (x *SubscribeToProject) Reset() {
	*x = SubscribeToProject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_entities_commands_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeToProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToProject) ProtoMessage() {}

func (x *SubscribeToProject) ProtoReflect() protoreflect.Message {
	mi := &file_common_entities_commands_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToProject.ProtoReflect.Descriptor instead.
func (*SubscribeToProject) Descriptor() ([]byte, []int) {
	return file_common_entities_commands_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeToProject) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SubscribeToProject) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

// Session-related messages
// Key-value-related messages
type AddSessionKeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *Header `protobuf:"bytes,1,opt,name=header,proto3,oneof" json:"header,omitempty"`
	SessionId string  `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Key       string  `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value     string  `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AddSessionKeyValue) Reset() {
	*x = AddSessionKeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_entities_commands_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSessionKeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSessionKeyValue) ProtoMessage() {}

func (x *AddSessionKeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_common_entities_commands_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSessionKeyValue.ProtoReflect.Descriptor instead.
func (*AddSessionKeyValue) Descriptor() ([]byte, []int) {
	return file_common_entities_commands_proto_rawDescGZIP(), []int{4}
}

func (x *AddSessionKeyValue) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AddSessionKeyValue) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddSessionKeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AddSessionKeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DeleteSessionKeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *Header `protobuf:"bytes,1,opt,name=header,proto3,oneof" json:"header,omitempty"`
	SessionId string  `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Key       string  `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DeleteSessionKeyValue) Reset() {
	*x = DeleteSessionKeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_entities_commands_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSessionKeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionKeyValue) ProtoMessage() {}

func (x *DeleteSessionKeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_common_entities_commands_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionKeyValue.ProtoReflect.Descriptor instead.
func (*DeleteSessionKeyValue) Descriptor() ([]byte, []int) {
	return file_common_entities_commands_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSessionKeyValue) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DeleteSessionKeyValue) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DeleteSessionKeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ModifySessionKeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *Header `protobuf:"bytes,1,opt,name=header,proto3,oneof" json:"header,omitempty"`
	SessionId string  `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Key       string  `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value     string  `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ModifySessionKeyValue) Reset() {
	*x = ModifySessionKeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_entities_commands_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifySessionKeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifySessionKeyValue) ProtoMessage() {}

func (x *ModifySessionKeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_common_entities_commands_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifySessionKeyValue.ProtoReflect.Descriptor instead.
func (*ModifySessionKeyValue) Descriptor() ([]byte, []int) {
	return file_common_entities_commands_proto_rawDescGZIP(), []int{6}
}

func (x *ModifySessionKeyValue) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ModifySessionKeyValue) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ModifySessionKeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ModifySessionKeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Session name-related messages
type ModifySessionName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *Header `protobuf:"bytes,1,opt,name=header,proto3,oneof" json:"header,omitempty"`
	SessionId string  `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Name      string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ModifySessionName) Reset() {
	*x = ModifySessionName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_entities_commands_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifySessionName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifySessionName) ProtoMessage() {}

func (x *ModifySessionName) ProtoReflect() protoreflect.Message {
	mi := &file_common_entities_commands_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifySessionName.ProtoReflect.Descriptor instead.
func (*ModifySessionName) Descriptor() ([]byte, []int) {
	return file_common_entities_commands_proto_rawDescGZIP(), []int{7}
}

func (x *ModifySessionName) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ModifySessionName) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ModifySessionName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Session heartbeat-related messages
type UpdateSessionHeartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *Header `protobuf:"bytes,1,opt,name=header,proto3,oneof" json:"header,omitempty"`
	SessionId string  `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
}

func (x *UpdateSessionHeartbeat) Reset() {
	*x = UpdateSessionHeartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_entities_commands_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSessionHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionHeartbeat) ProtoMessage() {}

func (x *UpdateSessionHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_common_entities_commands_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionHeartbeat.ProtoReflect.Descriptor instead.
func (*UpdateSessionHeartbeat) Descriptor() ([]byte, []int) {
	return file_common_entities_commands_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateSessionHeartbeat) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UpdateSessionHeartbeat) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_common_entities_commands_proto protoreflect.FileDescriptor

var file_common_entities_commands_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x1c, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x99, 0x01, 0x0a, 0x0d, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x2d, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x22, 0x67, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x2d, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x49, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x6c, 0x0a,
	0x12, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x6f, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x88,
	0x01, 0x01, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x42, 0x09, 0x0a, 0x07, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x6c, 0x0a, 0x12, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x6f, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x12, 0x2d, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x94, 0x01, 0x0a, 0x12, 0x41, 0x64,
	0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x2d, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x22, 0x81, 0x01, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x22, 0x97, 0x01, 0x0a, 0x15, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2d,
	0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x48, 0x00, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x7f,
	0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x88,
	0x01, 0x01, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22,
	0x70, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x2d, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x56, 0x69, 0x70, 0x57, 0x57, 0x2f, 0x6d, 0x61, 0x6c, 0x67, 0x6f, 0x2d, 0x63, 0x32, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_entities_commands_proto_rawDescOnce sync.Once
	file_common_entities_commands_proto_rawDescData = file_common_entities_commands_proto_rawDesc
)

func file_common_entities_commands_proto_rawDescGZIP() []byte {
	file_common_entities_commands_proto_rawDescOnce.Do(func() {
		file_common_entities_commands_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_entities_commands_proto_rawDescData)
	})
	return file_common_entities_commands_proto_rawDescData
}

var file_common_entities_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_common_entities_commands_proto_goTypes = []interface{}{
	(*CreateCommand)(nil),          // 0: entities.CreateCommand
	(*CancelCommand)(nil),          // 1: entities.CancelCommand
	(*SubscribeToSession)(nil),     // 2: entities.SubscribeToSession
	(*SubscribeToProject)(nil),     // 3: entities.SubscribeToProject
	(*AddSessionKeyValue)(nil),     // 4: entities.AddSessionKeyValue
	(*DeleteSessionKeyValue)(nil),  // 5: entities.DeleteSessionKeyValue
	(*ModifySessionKeyValue)(nil),  // 6: entities.ModifySessionKeyValue
	(*ModifySessionName)(nil),      // 7: entities.ModifySessionName
	(*UpdateSessionHeartbeat)(nil), // 8: entities.UpdateSessionHeartbeat
	(*Header)(nil),                 // 9: entities.Header
}
var file_common_entities_commands_proto_depIdxs = []int32{
	9, // 0: entities.CreateCommand.header:type_name -> entities.Header
	9, // 1: entities.CancelCommand.header:type_name -> entities.Header
	9, // 2: entities.SubscribeToSession.header:type_name -> entities.Header
	9, // 3: entities.SubscribeToProject.header:type_name -> entities.Header
	9, // 4: entities.AddSessionKeyValue.header:type_name -> entities.Header
	9, // 5: entities.DeleteSessionKeyValue.header:type_name -> entities.Header
	9, // 6: entities.ModifySessionKeyValue.header:type_name -> entities.Header
	9, // 7: entities.ModifySessionName.header:type_name -> entities.Header
	9, // 8: entities.UpdateSessionHeartbeat.header:type_name -> entities.Header
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_common_entities_commands_proto_init() }
func file_common_entities_commands_proto_init() {
	if File_common_entities_commands_proto != nil {
		return
	}
	file_common_entities_header_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_common_entities_commands_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_entities_commands_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_entities_commands_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeToSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_entities_commands_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeToProject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_entities_commands_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSessionKeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_entities_commands_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSessionKeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_entities_commands_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifySessionKeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_entities_commands_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifySessionName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_entities_commands_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSessionHeartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_common_entities_commands_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_common_entities_commands_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_common_entities_commands_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_common_entities_commands_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_common_entities_commands_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_common_entities_commands_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_common_entities_commands_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_common_entities_commands_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_common_entities_commands_proto_msgTypes[8].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_entities_commands_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_entities_commands_proto_goTypes,
		DependencyIndexes: file_common_entities_commands_proto_depIdxs,
		MessageInfos:      file_common_entities_commands_proto_msgTypes,
	}.Build()
	File_common_entities_commands_proto = out.File
	file_common_entities_commands_proto_rawDesc = nil
	file_common_entities_commands_proto_goTypes = nil
	file_common_entities_commands_proto_depIdxs = nil
}
