name: Playwright Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Setup database
        run: bun run migrate
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps
      - name: Build the app
        run: bun run build
      - name: Run Playwright tests
        run: bun run test:e2e
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
          DEFAULT_ADMIN_EMAIL: admin@admin.com
          DEFAULT_ADMIN_PASSWORD: admin
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
